import {mountAreaMap} from './area-map.js?v=20260915-map2';
import {solar,rect,inside,shadowPolygons,shadeAt,makeDemo} from './model.js?v=20260915-map2';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={lat:41.4005,lon:2.1572,zone:'Europe/Madrid',date:'2026-06-21',minute:840,buildings:makeDemo(),trees:[[-42,-23],[-35,-25],[-27,-27],[35,30],[43,29],[48,22]].map(([x,y])=>({x,y,type:'tree'})),added:[],view:'shadows',tool:null,selected:null,angle:-.35,zoom:1,source:'Illustrative teaching model',name:'Plaça de la Vila de Gràcia',city:'Barcelona, Spain'};
const canvas=$('#scene'),ctx=canvas.getContext('2d');let moving=null;let W=800,H=450,scale=3,origin=[400,240],sun,playing=false,frame=0,heat=[],baseHeat=[],samples=[],metrics={},pointer=null,drag=null,dragged=false,heatTimer;
function project(x,y,z=0){const c=Math.cos(state.angle),s=Math.sin(state.angle),a=x*c-y*s,b=x*s+y*c;return [origin[0]+a*scale,origin[1]+b*scale*.53-z*scale*.88]}
function unproject(x,y){const a=(x-origin[0])/scale,b=(y-origin[1])/(scale*.53),c=Math.cos(state.angle),s=Math.sin(state.angle);return {x:a*c+b*s,y:-a*s+b*c}}
function polygon(p,color,stroke){ctx.beginPath();p.forEach((a,i)=>{const q=project(...a);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=.7;ctx.stroke()}}
function prism(p,h,color='#ffffff'){let faces=p.map((a,i)=>{let b=p[(i+1)%p.length];return {p:[[...a,0],[...b,0],[...b,h],[...a,h]],depth:project((a[0]+b[0])/2,(a[1]+b[1])/2)[1],tone:i%2?'#cad6d1':'#e3ebe6'}}).sort((a,b)=>a.depth-b.depth);faces.forEach(f=>polygon(f.p,f.tone,'#c1d0c7'));polygon(p.map(a=>[...a,h]),color,'#d6e0d9')}
function tree(t){const p=project(t.x,t.y,0),q=project(t.x,t.y,7);ctx.strokeStyle='#8b8d6c';ctx.lineWidth=2*scale/3;ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(...q);ctx.stroke();const r=4*scale;let g=ctx.createRadialGradient(q[0]-r*.3,q[1]-r*.5,1,q[0],q[1],r);g.addColorStop(0,t.added?'#75bd87':'#8db08b');g.addColorStop(1,t.added?'#2f8154':'#56825f');ctx.beginPath();ctx.ellipse(q[0],q[1],r,r*.84,0,0,Math.PI*2);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='#647c4830';ctx.stroke();}
function pergola(t){for(const [x,y] of rect(t.x,t.y,8,6)){ctx.beginPath();ctx.moveTo(...project(x,y));ctx.lineTo(...project(x,y,3));ctx.strokeStyle='#7f8968';ctx.lineWidth=Math.max(1,scale*.45);ctx.stroke()}polygon(rect(t.x,t.y,8,6).map(p=>[...p,3]),'#b0ba89','#7e9064');for(let x=t.x-3;x<t.x+4;x+=1){ctx.beginPath();ctx.moveTo(...project(x,t.y-3,3.1));ctx.lineTo(...project(x,t.y+3,3.1));ctx.strokeStyle='#879965';ctx.lineWidth=1;ctx.stroke()}}
function renderScene(after,ox,width){ctx.save();ctx.beginPath();ctx.rect(ox,0,width,H);ctx.clip();origin=[ox+width/2,H*.51+18];scale=Math.min(width/250,H/170)*state.zoom;polygon(rect(0,0,180,180).map(p=>[...p,-2]),'#c9d7ce');prism(rect(0,0,180,180),0,'#e8eee6');for(let x=-90;x<=90;x+=6){ctx.beginPath();ctx.moveTo(...project(x,-90));ctx.lineTo(...project(x,90));ctx.strokeStyle='#d4dac646';ctx.lineWidth=.6;ctx.stroke();ctx.beginPath();ctx.moveTo(...project(-90,x));ctx.lineTo(...project(90,x));ctx.stroke()}if(state.source.includes('Illustrative')){polygon(rect(0,0,94,83),'#f1efe3','#d7dac7');polygon(rect(0,48,178,9),'#d9ddcd');polygon(rect(-54,0,9,178),'#d9ddcd');for(let x=-38;x<40;x+=9)for(let y=-30;y<32;y+=9)polygon(rect(x,y,8.9,8.9),'#e8e7d733','#d9dcc757')}
const objects=[...state.trees,...(after?state.added:[])];if(state.view==='heatmap'){const hm=after?heat:baseHeat;for(let i=0;i<samples.length;i++){const t=(hm[i]||0)/10;const c=[237-166*t,219-109*t,163-62*t].map(Math.round);polygon(rect(samples[i].x,samples[i].y,3.04,3.04),`rgb(${c.join(',')})`)}}
if(sun.up>0){ctx.save();ctx.beginPath();rect(0,0,180,180).forEach((p,i)=>{const q=project(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();ctx.clip();const polys=shadowPolygons(state.buildings,objects,sun);ctx.save();ctx.globalAlpha=state.view==='heatmap'?.13:.34;ctx.beginPath();for(const poly of polys){poly.forEach((p,i)=>{const q=project(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath()}ctx.fillStyle='#52634f';ctx.fill('nonzero');ctx.restore();ctx.restore()}else{polygon(rect(0,0,180,180),'#62798b66')}
const drawables=[...state.buildings.map(b=>({kind:'building',item:b,depth:Math.max(...b.p.map(p=>project(...p)[1]))})),...objects.map(t=>({kind:t.type,item:t,depth:project(t.x,t.y)[1]}))].sort((a,b)=>a.depth-b.depth);drawables.forEach(o=>{if(o.kind==='building')prism(o.item.p,o.item.h);else if(o.kind==='tree')tree(o.item);else pergola(o.item)});
if(after&&state.selected!==null&&state.added[state.selected]){const t=state.added[state.selected];ctx.setLineDash([3,3]);polygon(rect(t.x,t.y,11,11),'#a8ba7030','#496936');ctx.setLineDash([])}if(after&&state.tool&&pointer&&validPoint(pointer)){ctx.globalAlpha=.65;const t={...pointer,type:state.tool,added:true};t.type==='tree'?tree(t):pergola(t);ctx.globalAlpha=1;polygon(rect(t.x,t.y,state.tool==='tree'?8:8,state.tool==='tree'?8:6),'#a8ba7020','#7b9354')}
ctx.restore()}
function render(){$('.north b').style.transform='rotate('+Math.atan2(Math.sin(state.angle),.53*Math.cos(state.angle))*180/Math.PI+'deg)';ctx.clearRect(0,0,W,H);if(state.view==='compare'){renderScene(false,0,W/2);renderScene(true,W/2,W/2);ctx.beginPath();ctx.moveTo(W/2,65);ctx.lineTo(W/2,H-40);ctx.strokeStyle='#b6c2a5';ctx.lineWidth=1;ctx.setLineDash([4,5]);ctx.stroke();ctx.setLineDash([])}else renderScene(true,0,W);$('#scale').textContent='20 m';$('#scale').style.borderTop='1px solid #829171';$('#scale').style.width=(20*scale)+'px';$('#scale').style.paddingTop='4px';}
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;const d=Math.min(devicePixelRatio,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);render()}
function rebuildSamples(){samples=[];for(let x=-88.5;x<90;x+=3)for(let y=-88.5;y<90;y+=3)if(!state.buildings.some(b=>inside(x,y,b.p)))samples.push({x,y})}
function update(){sun=solar(state);const before=shadeAt(samples,state.buildings,state.trees,sun),after=shadeAt(samples,state.buildings,[...state.trees,...state.added],sun);metrics={before,after};const labels=document.querySelectorAll('#compare-labels small');labels[0].textContent=sun.up>0?before.toFixed(1)+'% shaded':'Night';labels[1].textContent=sun.up>0?after.toFixed(1)+'% shaded':'Night';$('#clock').textContent=`${String(Math.floor(state.minute/60)).padStart(2,'0')}:${String(state.minute%60).padStart(2,'0')}`;$('#time').value=state.minute;$('#shade').textContent=sun.up>0?Math.round(after):'—';$('#coverage').style.width=(sun.up>0?after:0)+'%';$('#exposed').textContent=sun.up>0?`${Math.round(100-after)}% sunlit`:'Sun below horizon';$('#elevation').innerHTML=`${sun.elevation.toFixed(1)}<small>°</small>`;$('#azimuth').textContent=`Azimuth ${Math.round(sun.azimuth)}° · from north`;$('#sun-height').textContent=`Solar elevation ${Math.round(sun.elevation)}°`;$('#zone-label').textContent=`LOCAL TIME · UTC${sun.offset>=0?'+':''}${sun.offset}`;$('#delta').hidden=!state.added.length||sun.up<=0;$('#delta').textContent=`+${Math.max(0,after-before).toFixed(1)} pp`;$('#count').textContent=`${state.added.length} added`;$('#undo').disabled=$('#clear').disabled=!state.added.length;$('#insight').textContent=sun.up<=0?'The sun is below the horizon. Nighttime is excluded from shade-duration analysis.':state.added.length?`Your design shades ${after.toFixed(1)}% of open ground, compared with ${before.toFixed(1)}% before. Keep experimenting.`:state.view==='heatmap'?'Darker ground receives more shade between 08:00 and 18:00. Try placing a canopy in a light area.':'Move through the day to discover where shade is needed most.';render()}
function analyse(){baseHeat=Array(samples.length).fill(0);heat=Array(samples.length).fill(0);for(let minute=495;minute<1080;minute+=30){const s=solar({...state,minute});if(s.up<=0)continue;const before=shadowPolygons(state.buildings,state.trees,s);const added=shadowPolygons([],state.added,s);for(let i=0;i<samples.length;i++){const p=samples[i],b=before.some(poly=>inside(p.x,p.y,poly));if(b)baseHeat[i]+=.5;if(b||added.some(poly=>inside(p.x,p.y,poly)))heat[i]+=.5}}const avg=heat.reduce((a,b)=>a+b,0)/(heat.length||1);$('#duration').innerHTML=`${avg.toFixed(1)} <small>h</small>`;render()}
function scheduleAnalysis(){clearTimeout(heatTimer);$('#duration').innerHTML='…';heatTimer=setTimeout(analyse,50)}
function validPoint(t){const r=state.tool==='pergola'?5:4;return Math.abs(t.x)<90-r&&Math.abs(t.y)<90-r&&!rect(t.x,t.y,r*2,r*2).concat([[t.x,t.y]]).some(p=>state.buildings.some(b=>inside(...p,b.p)))}
function selectTool(type){moving=null;state.tool=state.tool===type?null:type;state.selected=null;syncSelection();$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.tool));$('#hint').textContent=state.tool?`Click open ground to place a ${state.tool} · Esc to cancel`:'Drag to orbit · Scroll to zoom';canvas.style.cursor=state.tool?'crosshair':'grab';render()}
function syncSelection(){$('#selection').hidden=state.selected===null;if(state.selected!==null)$('#selection-label').textContent=`${state.added[state.selected]?.type==='tree'?'Tree':'Pergola'} selected`}
function setView(view){state.view=view;$$('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));$('#compare-labels').hidden=view!=='compare';$('#heat-legend').hidden=view!=='heatmap';update()}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));$('#compare').onclick=()=>setView(state.view==='compare'?'shadows':'compare');$('#time').oninput=e=>{state.minute=+e.target.value;update()};$('#date').onchange=e=>{if(!e.target.value)return;state.date=e.target.value;$('#season').value=['06-21','09-22','12-21','03-20'].includes(state.date.slice(5))?state.date.slice(5):'custom';update();scheduleAnalysis()};$('#season').onchange=e=>{if(e.target.value==='custom')return;state.date=state.date.slice(0,4)+'-'+e.target.value;$('#date').value=state.date;update();scheduleAnalysis()};$('#play').onclick=()=>{playing=!playing;$('#play').textContent=playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',playing?'Pause time animation':'Play time animation');if(playing)tick()};function tick(){if(!playing)return;state.minute=(state.minute+5)%1440;update();frame=setTimeout(tick,120)}
canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,angle:state.angle};dragged=false};canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();pointer=unproject(e.clientX-r.left,e.clientY-r.top);if(drag&&!state.tool){const dx=e.clientX-drag.x;if(Math.abs(dx)>3)dragged=true;state.angle=drag.angle+dx*.007}render()};canvas.onpointerup=e=>{if(!dragged){const r=canvas.getBoundingClientRect();if(state.view==='compare'&&e.clientX-r.left<W/2){$('#hint').textContent='Place interventions in the AFTER view on the right.';drag=null;return}pointer=unproject(e.clientX-r.left,e.clientY-r.top);if(state.tool){if(validPoint(pointer)){if(moving!==null){state.added[moving]={...pointer,type:state.tool,added:true};moving=null;state.tool=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.remove('active'));$('#hint').textContent='Element moved · Drag to orbit'}else state.added.push({...pointer,type:state.tool,added:true});update();scheduleAnalysis()}else $('#hint').textContent='Choose open ground inside the study area.'}else{state.selected=state.added.findIndex(t=>Math.hypot(t.x-pointer.x,t.y-pointer.y)<7);if(state.selected<0)state.selected=null;syncSelection();render()}}drag=null};canvas.onpointercancel=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();state.zoom=Math.max(.65,Math.min(2,state.zoom-e.deltaY*.001));render()};canvas.onkeydown=e=>{if(e.key==='Escape'){selectTool(state.tool);return}if(state.tool&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter'].includes(e.key)){e.preventDefault();pointer??={x:0,y:0};if(e.key==='Enter'&&validPoint(pointer)){if(moving!==null){state.added[moving]={...pointer,type:state.tool,added:true};moving=null;state.tool=null;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.remove('active'));$('#hint').textContent='Element moved · Drag to orbit'}else state.added.push({...pointer,type:state.tool,added:true});update();scheduleAnalysis()}else{pointer.x+=e.key==='ArrowLeft'?-3:e.key==='ArrowRight'?3:0;pointer.y+=e.key==='ArrowUp'?-3:e.key==='ArrowDown'?3:0;render()}}};$('#rotate').onclick=()=>{state.angle+=Math.PI/6;render()};$('#zoom-in').onclick=()=>{state.zoom=Math.min(2,state.zoom+.15);render()};$('#zoom-out').onclick=()=>{state.zoom=Math.max(.65,state.zoom-.15);render()};$('#reset-view').onclick=()=>{state.angle=-.35;state.zoom=1;render()};function designChanged(){state.selected=null;syncSelection();update();scheduleAnalysis()}$('#undo').onclick=()=>{state.added.pop();designChanged()};$('#clear').onclick=()=>{state.added=[];designChanged()};$('#remove').onclick=()=>{state.added.splice(state.selected,1);designChanged()};$('#duplicate').onclick=()=>{const t=state.added[state.selected];selectTool(t.type);pointer={x:t.x+10,y:t.y};render()};$('#move').onclick=()=>{const index=state.selected,t=state.added[index];selectTool(t.type);moving=index;pointer={x:t.x,y:t.y};$('#hint').textContent='Click a new position · Esc keeps the original';render()};
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());function about(){$('#data-detail').textContent=`Current scene: ${state.source}. ${state.buildings.length} buildings; ${state.buildings.filter(b=>b.known).length} tagged heights, ${state.buildings.filter(b=>!b.known).length} estimated heights. The illustrative fallback is a synthetic square, not a reconstruction of the selected location.`;$('#about-dialog').showModal()}$('#help').onclick=$('#method').onclick=about;
$('#choose').onclick=()=>{$('#map-dialog').showModal();drawMap()};
rebuildSamples();sun=solar(state);new ResizeObserver(resize).observe(canvas);update();scheduleAnalysis();
const places=[{lat:41.4005,lon:2.1572,zone:'Europe/Madrid',name:'Plaça de la Vila de Gràcia',city:'Barcelona, Spain'},{lat:52.5423,lon:13.4204,zone:'Europe/Berlin',name:'Helmholtzplatz',city:'Berlin, Germany'},{lat:55.6790,lon:12.5743,zone:'Europe/Copenhagen',name:'Gråbrødretorv',city:'Copenhagen, Denmark'}];
let pending={...places[0]},loading=false;
function syncMapFields(){$('#lat').value=pending.lat.toFixed(5);$('#lon').value=pending.lon.toFixed(5);$('#timezone').value=pending.zone}
const areaMap=mountAreaMap({getSelection:()=>pending,isLoading:()=>loading,setSelection:p=>{pending={...pending,...p};syncMapFields();$$('[data-place]').forEach(b=>b.classList.remove('selected'))}});
function drawMap(){syncMapFields();areaMap.render()}
$$('[data-place]').forEach(b=>b.onclick=()=>{if(loading)return;pending={...places[+b.dataset.place]};$$('[data-place]').forEach(a=>a.classList.toggle('selected',a===b));syncMapFields();areaMap.fit()});
for(const id of ['lat','lon'])$('#'+id).onchange=()=>{if(loading)return;const lat=Number($('#lat').value),lon=Number($('#lon').value);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>66||Math.abs(lon)>180){$('#load-status').textContent='Enter latitude −66 to 66 and longitude −180 to 180.';return}pending={...pending,lat,lon,name:'Custom study area',city:'Selected coordinates'};$$('[data-place]').forEach(b=>b.classList.remove('selected'));areaMap.fit()};$('#timezone').onchange=e=>pending.zone=e.target.value;
function parseHeight(tags){const text=String(tags.height||'').trim();let h=/^\d+(\.\d+)?\s*(m|meters|metres)?$/.test(text)?parseFloat(text):/^\d+(\.\d+)?\s*(ft|feet|')$/.test(text)?parseFloat(text)*.3048:NaN;if(Number.isFinite(h)&&h>0&&h<400)return {h,known:true,heightSource:'height tag'};const levels=Number(tags['building:levels']);return {h:levels>0&&levels<100?levels*3:12,known:false,heightSource:levels>0?'levels × 3 m':'12 m fallback'}}
function parseOSM(data,area){const mx=111320*Math.cos(area.lat*Math.PI/180),my=111320,toPoint=g=>[(g.lon-area.lon)*mx,-(g.lat-area.lat)*my];const buildings=data.elements.filter(e=>e.type==='way'&&e.tags?.building&&e.tags.building!=='no'&&e.geometry?.length>=4).map(e=>({id:e.id,p:e.geometry.slice(0,-1).map(toPoint),...parseHeight(e.tags)})).filter(b=>b.p.length>=3&&b.p.some(p=>Math.abs(p[0])<110&&Math.abs(p[1])<110));const trees=data.elements.filter(e=>e.type==='node'&&e.tags?.natural==='tree').map(e=>{const [x,y]=toPoint(e);return {x,y,type:'tree'}}).filter(t=>Math.abs(t.x)<86&&Math.abs(t.y)<86);return {buildings,trees}}
async function generate(){if(loading)return;const lat=Number($('#lat').value),lon=Number($('#lon').value);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>66||Math.abs(lon)>180){$('#load-status').textContent='Please enter valid study coordinates.';return}pending.lat=lat;pending.lon=lon;pending.zone=$('#timezone').value;const area={...pending};loading=true;$('#generate').disabled=true;$('#generate').textContent='Generating…';$('#load-status').textContent='Reading open building footprints and height tags…';let model,source;try{if(Math.abs(area.lat-41.4005)<.00002&&Math.abs(area.lon-2.1572)<.00002){const cached=await fetch('./barcelona-osm.json');if(!cached.ok)throw Error('Snapshot unavailable');model=parseOSM(await cached.json(),area);source='OpenStreetMap · snapshot 14 Sep 2026'}else{const d=.0023,dx=d/Math.cos(area.lat*Math.PI/180),bbox=[area.lat-d,area.lon-dx,area.lat+d,area.lon+dx].join(',');const query=`[out:json][timeout:18];(way[building](${bbox});node[natural=tree](${bbox}););out geom;`;const response=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:new URLSearchParams({data:query}),signal:AbortSignal.timeout(23000)});if(!response.ok)throw Error('Map service unavailable');model=parseOSM(await response.json(),area);if(!model.buildings.length)throw Error('No usable building footprints');source='OpenStreetMap · live footprints'}}catch{model={buildings:makeDemo(),trees:state.trees.filter(t=>Math.abs(t.x)<80&&Math.abs(t.y)<80)};source='Illustrative teaching model';$('#load-status').textContent='Live footprints unavailable. Opening a labelled teaching model.'}Object.assign(state,area,{buildings:model.buildings,trees:model.trees,source,added:[],selected:null,tool:null,zoom:1,angle:-.35});$('#place').textContent=state.name;$('#coords').textContent=`${state.city} · ${Math.abs(state.lat).toFixed(4)}° ${state.lat<0?'S':'N'}, ${Math.abs(state.lon).toFixed(4)}° ${state.lon<0?'W':'E'}`;$('#model-source').textContent=source;$$('[data-tool]').forEach(b=>b.classList.remove('active'));syncSelection();rebuildSamples();update();scheduleAnalysis();$('#hint').textContent=source.includes('Illustrative')?'Live data unavailable · illustrative geometry, location-based sun':'Urban model ready · Drag to orbit · Scroll to zoom';loading=false;$('#generate').disabled=false;$('#generate').innerHTML='Generate urban model <span>↗</span>';$('#map-dialog').close()}
$('#generate').onclick=generate;
const agentTools=[{name:'read_sunspace_analysis',description:'Read current site, solar settings and before/after open-ground shade percentages.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({location:{lat:state.lat,lon:state.lon},date:state.date,minute:state.minute,source:state.source,daylight:sun.up>0,shadePercent:metrics,interventions:state.added.length})},{name:'set_sunspace_time',description:'Set the simulation date and local minute of day and update the visible shadow analysis.',inputSchema:{type:'object',properties:{date:{type:'string'},minute:{type:'integer',minimum:0,maximum:1435}},required:['date','minute'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(input.date)||!Number.isFinite(Date.parse(input.date))||new Date(input.date).toISOString().slice(0,10)!==input.date||!Number.isInteger(input.minute)||input.minute<0||input.minute>1435)throw Error('Valid ISO date and minute 0–1435 required');state.date=input.date;state.minute=input.minute;$('#date').value=state.date;$('#season').value=['06-21','09-22','12-21','03-20'].includes(state.date.slice(5))?state.date.slice(5):'custom';update();analyse();return {date:state.date,minute:state.minute,shadePercent:metrics}}}];
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of agentTools)try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}


// Begin with a map; closing it opens the illustrative teaching sandbox.
$('#map-dialog').showModal();drawMap();
