// OpenStreetMap ground features, in local metres: east +x, south +y.
import {inside} from './model.js?v=20260915-context1';
export const palette={land:'#deded2',green:'#b6cda2',forest:'#95b58c',water:'#86bcc9',sand:'#e8d6ac',paved:'#e8ddc6',road:'#abb5b5',path:'#e6d6b8',rail:'#909a9a'};
const near=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1])<.03;
export function joinRings(parts){const remaining=parts.filter(p=>p.length>1).map(p=>p.slice()),rings=[];let incomplete=0;while(remaining.length){let ring=remaining.pop(),changed=true;while(!near(ring[0],ring.at(-1))&&changed){changed=false;for(let i=0;i<remaining.length;i++){const p=remaining[i];if(near(ring.at(-1),p[0]))ring.push(...p.slice(1));else if(near(ring.at(-1),p.at(-1)))ring.push(...p.slice(0,-1).reverse());else if(near(ring[0],p.at(-1)))ring=p.slice(0,-1).concat(ring);else if(near(ring[0],p[0]))ring=p.slice(1).reverse().concat(ring);else continue;remaining.splice(i,1);changed=true;break}}if(ring.length>=4&&near(ring[0],ring.at(-1)))rings.push(ring.slice(0,-1));else incomplete++}return {rings,incomplete}}
function classify(t){if(t.natural==='water'||t.water||t.waterway==='riverbank'||['reservoir','basin'].includes(t.landuse)||t.leisure==='swimming_pool'||t.amenity==='fountain')return 'water';if(['wood','scrub'].includes(t.natural)||t.landuse==='forest')return 'forest';if(['grassland','heath','wetland'].includes(t.natural)||['grass','meadow','village_green','recreation_ground','allotments','orchard','vineyard','farmland'].includes(t.landuse)||['park','garden','playground','pitch','golf_course','recreation_ground'].includes(t.leisure))return 'green';if(['sand','beach','bare_rock','scree'].includes(t.natural))return 'sand';if(t['area:highway'])return ['pedestrian','footway'].includes(t['area:highway'])?'paved':'road';if(t.highway&&t.area==='yes')return ['pedestrian','footway','path','steps'].includes(t.highway)?'paved':'road';if(['parking','school','university','college','hospital'].includes(t.amenity)||['sports_centre','stadium'].includes(t.leisure))return 'paved';if(t.landuse)return 'land';return null}
function measure(s){const m=String(s??'').trim().match(/^(\d+(?:\.\d+)?)\s*(m|ft|')?$/);return m?+m[1]*(m[2]==='ft'||m[2]==="'"?.3048:1):NaN}
export function roadWidth(t){const width=measure(t.width);if(width>0&&width<150)return {width,estimated:false};const defaults={motorway:14,trunk:12,primary:10,secondary:9,tertiary:8,residential:6,unclassified:6,living_street:5,service:4,pedestrian:6,footway:2,path:2,cycleway:2.5,steps:2,track:3};const lanes=Number(t.lanes);return {width:lanes>0&&lanes<=12?lanes*3:defaults[t.highway]||4,estimated:true}}
export const groupOf=kind=>['green','forest'].includes(kind)?'green':['road','path','rail'].includes(kind)?'roads':kind==='water'?'water':'surfaces';
export function contextQuery(lat,lon){const d=.0023,dx=d/Math.cos(lat*Math.PI/180),b=[lat-d,lon-dx,lat+d,lon+dx].join(',');return `[out:json][timeout:25][maxsize:25000000];is_in(${lat},${lon})->.cover;(nwr(${b})[~"^(building|highway|natural|landuse|leisure|water|waterway|railway|amenity|area:highway)$"~"."];way(pivot.cover)[natural=water];rel(pivot.cover)[natural=water];way(pivot.cover)[landuse];rel(pivot.cover)[landuse];);out geom;`}
export function parseContext(data,area){const mx=111320*Math.cos(area.lat*Math.PI/180),project=g=>[(g.lon-area.lon)*mx,-(g.lat-area.lat)*111320],features=[],used=new Set(),stats={incomplete:0,underground:0,coastlines:0};
 const intersects=p=>p.length&&Math.min(...p.map(q=>q[0]))<=100&&Math.max(...p.map(q=>q[0]))>=-100&&Math.min(...p.map(q=>q[1]))<=100&&Math.max(...p.map(q=>q[1]))>=-100;
 for(const e of data.elements||[]){const t=e.tags||{},kind=classify(t);if(e.type!=='relation'||t.type!=='multipolygon'||!kind)continue;const outer=joinRings((e.members||[]).filter(m=>m.role!=='inner'&&m.geometry).map(m=>m.geometry.filter(Boolean).map(project))),inner=joinRings((e.members||[]).filter(m=>m.role==='inner'&&m.geometry).map(m=>m.geometry.filter(Boolean).map(project)));stats.incomplete+=outer.incomplete+inner.incomplete;if(!outer.rings.length)continue;for(const ring of outer.rings){if(!intersects(ring))continue;const holes=inner.rings.filter(p=>inside(...p[0],ring));features.push({id:'relation/'+e.id,kind,group:groupOf(kind),rings:[ring,...holes],name:t.name||''})}for(const m of e.members||[])if(m.role!=='inner')used.add(m.ref)}
 for(const e of data.elements||[]){if(e.type!=='way'||!e.geometry?.length)continue;const t=e.tags||{},p=e.geometry.filter(Boolean).map(project);if(!intersects(p))continue;if(t.natural==='coastline'){stats.coastlines++;continue}if(t.tunnel==='yes'||t.location==='underground'){stats.underground++;continue}if(t.building&&t.building!=='no')continue;const closed=p.length>3&&near(p[0],p.at(-1)),kind=classify(t);if(closed&&kind&&!used.has(e.id)){features.push({id:'way/'+e.id,kind,group:groupOf(kind),rings:[p.slice(0,-1)],name:t.name||''});continue}if(t.highway&&t.area!=='yes'&&!['proposed','construction'].includes(t.highway)){const kind=['pedestrian','footway','path','cycleway','steps','track'].includes(t.highway)?'path':'road';features.push({id:'way/'+e.id,kind,group:'roads',line:p,...roadWidth(t),bridge:t.bridge==='yes',name:t.name||''})}else if(t.waterway&&t.waterway!=='riverbank'){const w=measure(t.width);features.push({id:'way/'+e.id,kind:'water',group:'water',line:p,width:w>0?w:t.waterway==='river'?12:3,estimated:!(w>0),name:t.name||''})}else if(['rail','tram','light_rail','narrow_gauge'].includes(t.railway)){features.push({id:'way/'+e.id,kind:'rail',group:'roads',line:p,width:2,estimated:true,name:t.name||''})}}
 return {features,stats};
}
export function inFeature(x,y,f){if(f.rings)return inside(x,y,f.rings[0])&&!f.rings.slice(1).some(p=>inside(x,y,p));for(let i=1;i<f.line.length;i++){const a=f.line[i-1],b=f.line[i],dx=b[0]-a[0],dy=b[1]-a[1],d=dx*dx+dy*dy,k=d?Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/d)):0;if(Math.hypot(x-a[0]-k*dx,y-a[1]-k*dy)<f.width/2)return true}return false}
export function drawContext(ctx,project,features,visible){ctx.save();ctx.beginPath();[[-90,-90],[90,-90],[90,90],[-90,90]].forEach((p,i)=>i?ctx.lineTo(...project(...p)):ctx.moveTo(...project(...p)));ctx.closePath();ctx.clip();
 const path=(rings,color)=>{ctx.beginPath();for(const p of rings){p.forEach((q,i)=>i?ctx.lineTo(...project(...q)):ctx.moveTo(...project(...q)));ctx.closePath()}ctx.fillStyle=color;ctx.fill('evenodd')};
 const area=f=>f.rings?Math.abs(f.rings[0].reduce((s,p,i,a)=>s+p[0]*a[(i+1)%a.length][1]-a[(i+1)%a.length][0]*p[1],0)):0;
 const layers=[...features.filter(f=>f.rings).sort((a,b)=>area(b)-area(a)),...features.filter(f=>f.line).sort((a,b)=>(a.kind==='water'?-1:0)-(b.kind==='water'?-1:0))];
 for(const f of layers){if(visible[f.group]===false)continue;const color=palette[f.kind];if(f.rings){path(f.rings,color);continue}for(let i=1;i<f.line.length;i++){const a=f.line[i-1],b=f.line[i],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(!len)continue;const nx=-dy/len*f.width/2,ny=dx/len*f.width/2;path([[[a[0]+nx,a[1]+ny],[b[0]+nx,b[1]+ny],[b[0]-nx,b[1]-ny],[a[0]-nx,a[1]-ny]]],color)}for(const p of f.line)path([Array.from({length:12},(_,i)=>[p[0]+Math.cos(i*Math.PI/6)*f.width/2,p[1]+Math.sin(i*Math.PI/6)*f.width/2])],color);if(f.kind==='rail'){ctx.beginPath();f.line.forEach((p,i)=>i?ctx.lineTo(...project(...p)):ctx.moveTo(...project(...p)));ctx.setLineDash([3,3]);ctx.strokeStyle='#e8eeee';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([])}}ctx.restore()}
